{% set name = "cruft" %}
{% set version = "2.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe7aaace048df17efc0e597c8035cb0deaa7a8734a86eb8c6cca5388971a2a42

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-cache-dir -vvv
  entry_points:
    - cruft = cruft._cli:app

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.8
  run:
    - python >=3.6.2
    - cookiecutter >=1.6,<2.0
    - gitpython >=3.0,<4.0
    - typer >=0.4.0,<0.5.0
    - click >=7.1.2,<9.0.0
    - importlib_metadata >=1.7.0

test:
  requires:
    - git
  imports:
    - cruft
    - cruft._commands
  commands:
    - cruft --help

about:
  home: https://github.com/cruft/cruft
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Maintain all the necessary boilerplate for packaging and building projects separate from the code you intentionally write.
  description: |
    Allows you to maintain all the necessary cruft for packaging and
    building projects separate from the code you intentionally write.
    Built on-top of CookieCutter.
  doc_url: https://cruft.github.io/cruft/
  dev_url: https://github.com/cruft/cruft

extra:
  recipe-maintainers:
    - Zeitsperre
    - samj1912
